import React, {useEffect, useMemo, useState} from 'react';
import {NativeStackScreenProps} from '@react-navigation/native-stack';
import {Button, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {OccupationPicker} from '../../components/survey/OccupationPicker';
import {getSurveySteps, isStepValid, needsOccupation, SurveyStepKey} from '../../logic/surveyFlow';
import {OnboardingStackParamList} from '../../navigation/OnboardingNavigator';
import {DailyCommitment, Goal, Level, SurveyAnswers, WeeklyGoal} from '../../types/onboarding';
import {colors, spacing, typography} from '../../theme';
import {ScreenShell} from './ScreenShell';

type Props = NativeStackScreenProps<OnboardingStackParamList, 'Survey'> & {answers: SurveyAnswers; onChange: React.Dispatch<React.SetStateAction<SurveyAnswers>>};
const levels: {key: Level; label: string}[] = [{key: 'a1', label: 'A1 Beginner'}, {key: 'a2', label: 'A2 Elementary'}, {key: 'b1', label: 'B1 Intermediate'}, {key: 'b2', label: 'B2 Upper-Intermediate'}, {key: 'c1', label: 'C1 Advanced'}, {key: 'unsure', label: 'Not sure yet'}];
const goals: {key: Goal; label: string; description: string}[] = [{key: 'work', label: 'Work & Career', description: 'Meetings, emails, presentations'}, {key: 'interview', label: 'Interview Prep', description: 'Sound confident under pressure'}, {key: 'travel', label: 'Travel', description: 'Order, ask, get around easily'}, {key: 'daily', label: 'Everyday Conversation', description: 'Casual, natural, fluent'}, {key: 'exam', label: 'Exam Prep', description: 'IELTS, TOEFL and more'}, {key: 'academic', label: 'Academic & Writing', description: 'Essays, reports, emails'}];
const daily: {key: DailyCommitment; label: string}[] = [{key: 'casual', label: '5 min · Casual'}, {key: 'regular', label: '10 min · Regular'}, {key: 'serious', label: '15 min · Serious'}, {key: 'intense', label: '20+ min · Intense'}];
const weekly: {key: WeeklyGoal; label: string}[] = [{key: 'easy', label: '20 words · Easy'}, {key: 'steady', label: '40 words · Steady'}, {key: 'challenge', label: '70 words · Challenging'}, {key: 'ambitious', label: '100 words · Ambitious'}];
const content: Record<SurveyStepKey, {title: string; subtext: string}> = {level: {title: 'What is your English level?', subtext: 'Choose the closest answer.'}, goals: {title: 'What are you learning for?', subtext: 'Choose one or more goals.'}, occupation: {title: 'What is your occupation?', subtext: 'We will personalize your work vocabulary.'}, daily: {title: 'How much time can you give daily?', subtext: 'You can change this later.'}, weekly: {title: 'Set your weekly word goal.', subtext: 'Keep it realistic and consistent.'}};

export function SurveyScreen({navigation, answers, onChange}: Props) {
  const steps = useMemo(() => getSurveySteps(answers), [answers]);
  const [index, setIndex] = useState(0);
  const step = steps[index];
  useEffect(() => { if (index >= steps.length) setIndex(steps.length - 1); }, [index, steps.length]);
  const set = (update: Partial<SurveyAnswers>) => onChange(current => ({...current, ...update}));
  const toggleGoal = (goal: Goal) => onChange(current => { const next = current.goals.includes(goal) ? current.goals.filter(item => item !== goal) : [...current.goals, goal]; return {...current, goals: next, ...(needsOccupation(next) ? {} : {occupation: null, occupationText: null})}; });
  const next = () => index === steps.length - 1 ? navigation.navigate('Notifications') : setIndex(index + 1);
  const back = () => index === 0 ? navigation.goBack() : setIndex(index - 1);
  return <ScreenShell><View style={styles.top}><Button title="Back" onPress={back} /><View style={styles.progress}>{steps.map((item, itemIndex) => <View key={item} style={[styles.segment, itemIndex <= index && styles.filled]} />)}</View></View><Text style={styles.eyebrow}>STEP {index + 1} OF {steps.length}</Text><Text style={styles.title}>{content[step].title}</Text><Text>{content[step].subtext}</Text><View style={styles.body}>{step === 'level' && <Options options={levels} selected={answers.level} onPress={key => set({level: key as Level})} />}{step === 'goals' && <Options options={goals} selected={answers.goals} onPress={key => toggleGoal(key as Goal)} />}{step === 'occupation' && <OccupationPicker value={answers.occupationText} onSelect={(occupation, occupationText) => set({occupation, occupationText})} onType={(occupation, occupationText) => set({occupation, occupationText: occupationText || null})} />}{step === 'daily' && <Options options={daily} selected={answers.daily} onPress={key => set({daily: key as DailyCommitment})} />}{step === 'weekly' && <Options options={weekly} selected={answers.weekly} onPress={key => set({weekly: key as WeeklyGoal})} />}</View><Button title="Continue" disabled={!isStepValid(step, answers)} onPress={next} /></ScreenShell>;
}
function Options({options, selected, onPress}: {options: {key: string; label: string; description?: string}[]; selected: string | string[] | null; onPress: (key: string) => void}) { const chosen = (key: string) => Array.isArray(selected) ? selected.includes(key) : selected === key; return <ScrollView>{options.map(option => <Pressable key={option.key} style={[styles.option, chosen(option.key) && styles.selected]} onPress={() => onPress(option.key)}><Text style={styles.optionTitle}>{option.label}</Text>{option.description ? <Text>{option.description}</Text> : null}</Pressable>)}</ScrollView>; }
const styles = StyleSheet.create({top: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm}, progress: {flex: 1, flexDirection: 'row', gap: 4}, segment: {height: 5, flex: 1, backgroundColor: colors.disabled}, filled: {backgroundColor: colors.primary}, eyebrow: {marginTop: spacing.md, fontWeight: '700', fontSize: typography.caption}, title: {fontSize: typography.heading, fontWeight: '700', marginTop: spacing.sm}, body: {flex: 1, marginVertical: spacing.lg}, option: {borderWidth: 1, borderColor: colors.border, borderRadius: 6, padding: spacing.md, marginBottom: spacing.sm}, selected: {backgroundColor: colors.selected, borderColor: colors.primary}, optionTitle: {fontWeight: '600'}});
